### ISSUE TITLE
Private and group chat blockage UI component

### ISSUE THREAD

**Issue by sergejsvisockis** [joejoe2/frontend#1]
As soon as both the private and group chat blockage functionality is implemented on the back-end side (https://github.com/joejoe2/spring-chat/issues/5) it's required to introduce a corresponding Vue component into the UI.

**Comment by joejoe2** [comment]
Added setting for private chat at 46517a903df0e5bd19b99c930e53c66818adcff7

**Comment by sergejsvisockis** [comment]
ok, looks good

**Comment by sergejsvisockis** [comment]
Now it remains to add a proper group chat participant blockage capability UI capability. Just like for the private settings was done already.

**Comment by sergejsvisockis** [comment]
@joejoe2 Now it remains to add a proper group chat participant blockage capability on the UI. Just like for the private settings was done already.

**Comment by joejoe2** [comment]
Since https://github.com/joejoe2/spring-chat/issues/5 was  completed, we have to add corresponding UI components for group chat.

**Comment by sergejsvisockis** [comment]
Fantastic! Sounds good ;)

**Comment by joejoe2** [comment]
See cb25061745c8481506994800391b05e42df91333. I also want to change ui in private chat to follow this style.

**Comment by sergejsvisockis** [comment]
I've left several comments under that revision.

The default boolean value is "false".

**Comment by joejoe2** [comment]
It seems there are some redundant reset because showAlert will be closed by user. 

I think if the error doesn't contain message, console.log() may be more reasonable.

**Comment by sergejsvisockis** [comment]
sure, let's leave it like it is.

**Comment by sergejsvisockis** [comment]
That's actually the case when two back-end engineers are trying to tackle the UI :D

**Comment by sergejsvisockis** [comment]
But, I have thought around - I still think we can move this else statement. Boolean default value is false and the text value is blank - ""

**Comment by joejoe2** [comment]
I removed that and replaced with console.log 5cd4f48

**Comment by sergejsvisockis** [comment]
Cool!

**Comment by sergejsvisockis** [comment]
But IMO it's not a good idea to output an error message into the console.... Instead, these have to be showcased on the UI as a popup or any other way.

It was fine like it was before although we can drop this "else" statement.

**Comment by joejoe2** [comment]
You're right. I forgot users can see console if they are smart enough.

**Comment by sergejsvisockis** [comment]
That's when two backend engineers are tackling the UI :D

**Comment by joejoe2** [comment]
Fixed in e77bf0b. Actually this is my first vue/frontend project, so there is a lot of immature code I think ... 😅

**Comment by sergejsvisockis** [comment]
Totally understand :D I myself have been working with the UI seriously/commercially as a freelancer back in 2012 to 2014. and when I stopped the first Angular version had been released :D Even now remember Angular 0.1.0 xD and that Google I/O presentation.

So, lotta things have changed. For now it is rarely when I am tackling the UI although engineering fundamentals help here since these apply to the UI as well :) And docs of course:) and outdated experience also :D

**Comment by sergejsvisockis** [comment]
Looks good now :)

**Comment by sergejsvisockis** [comment]
I think it looks good and for now, I have nothing more to add here at this point. At least in the scope of this feature.

I'm closing the issue. Feel free to reopen if I am missing something.

Thanks a lot for your collaboration! It was fun! :)

**Comment by sergejsvisockis** [comment]
@joejoe2 I've just noticed that the branch is not merged.

I think we can merge it.

**Comment by joejoe2** [comment]
In fact this repo is not for chat app thoroughly, I will rename the repo and split out the content in main branch. Then merge the current branch.

**Comment by joejoe2** [comment]
Done. I am closing this issue for now.

**Comment by sergejsvisockis** [comment]
Sounds good! Thanks! ;)
